### PR TITLE
Add a GTP frontend.

### PR DESCRIPTION
**Pull request by macfergus**
Refactor the GoModel into a separate engine and frontend.

Only implements the bare minimum of GTP; it's enough to play a game in
Sente Goban.

PS. I played it against GnuGo; it forgot to make any eyes and lost by 175 points.

### CODE REVIEW

**Comment by maxpumperla** [comment]
Wow, this is amazing work, thank you. I'll review first thing tomorrow morning. 

P.s.: Yeah, the state of the current model is really bad, we'll certainly have to do something about that.

**Comment by macfergus** [comment]
Oh yeah, I wasn't expecting much from just the small training set. It's actually really cool, cause even the early model does a lot of things that look like real go moves: push, hane, extend; it played out a ladder for a while (but failed to finish it off); it even learned a joseki. (This was trained on a little bit bigger training set than the example model)

**Comment by maxpumperla** [comment]
Great, I had the same impression. For me the next big hurdle is to utilize keras' ```fit_generator```for real-time data augmentation, as the current in-memory approach won't do. Once there's access to a larger amount of data this way, one can really start thinking about better and better models for this.

Also, I don't necessarily want to clone AlphaGo, but it would be nice to have a very first MC tree search component at some point. We'll see. 

What would you like to see next or what would you think is most urgent?

**Comment by macfergus** [comment]
Yup, fit_generator seems like the biggest immediate win, I had a lot of memory problems while training.

I am interested in contributing to an MCTS implementation. I have a fair amount of experience with MCTS (in a totally unrelated domain), so I might be able to knock out a rough version pretty quick.

I also thought it would be fun to train a network to figure out who won a game? Might be hard to beat the heuristics that something like OGS uses.

That's all my big ideas; there's also lots of little stuff of course, like letting the bot play as white, etc.

**Comment by EderSantana** [comment]
for the generator I have this hackable indexed generator: https://github.com/EderSantana/seya/blob/master/seya/data_utils.py#L153-L238
It can be used with hdf5 arrays for a simple off core solution for large datasets.

**Pull request merged**
