### PR TITLE
Fix travis build and re-enable tests.

### PR DESCRIPTION
**Pull request by macfergus**
I guess the problem was that nose was not installed directly in the conda test environment. Instead it came from somewhere else on the system, causing import path confusion.

### CODE REVIEW

**Comment by macfergus** [comment]
Argh. That fixes python 2.7 support. But the gomill library does not support python 3.

I'll merge this and start an issue to figure out what to do about gomill.

**Comment by maxpumperla** [comment]
That's strange, the build was OK for python 3 until recently:

https://travis-ci.org/maxpumperla/betago/jobs/125189067

**Comment by maxpumperla** [comment]
Looks good on travis

**Comment by macfergus** [comment]
I think it's cause the build didn't touch any code that touched gomill, until I added model_test.py.

(It doesn't use the gomill code directly, but it does import it)

**Comment by ddugovic** [comment]
Sorry for having encouraged us to support python 2.7 if that poses any challenge... I only installed using 2.7 to get scipy working, as I imagined getting python 3 to work would be difficult.

**Comment by macfergus** [comment]
@ddugovic No worries, I think we should make an effort to support both.

**Pull request merged**
